sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

before_script:
  - sh -e /etc/init.d/xvfb start
  - cd ./tmdmaker.releng/

script:
  - mvn -B clean install

after_success:
  - mvn coveralls:report
