language: java
dist: xenial
sudo: required

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

addons:
  apt:
    packages:
    - metacity

services:
  - xvfb

before_script:
  - metacity --sm-disable --replace 2> metacity.err &

script:
  - mvn -B -P 2019-09 clean install -Dtycho.disableP2Mirrors=true

after_success:
  - mvn -B -P 2019-09 jacoco:report coveralls:report
