language: java
jdk:
  - oraclejdk8
  - oraclejdk7

before_script: "cd ./tmdmaker.releng/"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - mvn clean install coveralls:report
