language: java
dist: xenial
sudo: required

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 3820x2160x24"
  
script:
  - travis_wait 30 mvn -B -P 2019-09 clean install -Dtycho.disableP2Mirrors=true

after_success:
  - mvn -B -P 2019-09 jacoco:report coveralls:report
