language: java
dist: xenial
os: linux

jdk:
  - openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 3840x2160x24 -dpi 240"
  
script:
  - mvn -B -P 2020-12 clean install -Dtycho.disableP2Mirrors=true

after_success:
  - mvn -B -P 2020-12 jacoco:report coveralls:report
