name: Create a release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true

jobs:
  build:
    name: Create Release
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -e -B -P 2023-06 clean verify -Dtycho.disableP2Mirrors=false -Dmaven.test.skip=true
 
    - name: release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}

    - name: upload artifacts
      uses: AButler/upload-release-assets@v2.0
      with:
          files: './releng/org.tmdmaker.releng.product/target/products/tmdmaker_*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
